# Shell variables
# Generated by 'wal'
wallpaper='/home/knassar702/Downloads/wal0.jpg'

# Special
background='#0f1213'
foreground='#dfe0df'
cursor='#dfe0df'

# Colors
color0='#0f1213'
color1='#4B4B49'
color2='#6A6660'
color3='#8D7558'
color4='#DFA950'
color5='#A7A6A3'
color6='#C3C0BC'
color7='#dfe0df'
color8='#9c9c9c'
color9='#4B4B49'
color10='#6A6660'
color11='#8D7558'
color12='#DFA950'
color13='#A7A6A3'
color14='#C3C0BC'
color15='#dfe0df'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
