--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/knassar702/Downloads/wal0.jpg"

-- Special
background="#0f1213"
foreground="#dfe0df"
cursor="#dfe0df"

-- Colors
color0="#0f1213"
color1="#4B4B49"
color2="#6A6660"
color3="#8D7558"
color4="#DFA950"
color5="#A7A6A3"
color6="#C3C0BC"
color7="#dfe0df"
color8="#9c9c9c"
color9="#4B4B49"
color10="#6A6660"
color11="#8D7558"
color12="#DFA950"
color13="#A7A6A3"
color14="#C3C0BC"
color15="#dfe0df"
